#!/bin/sh
 
git filter-branch --env-filter '
 
an="$GIT_AUTHOR_NAME"
am="$GIT_AUTHOR_EMAIL"
cn="$GIT_COMMITTER_NAME"
cm="$GIT_COMMITTER_EMAIL"
 
if [ "$GIT_COMMITTER_EMAIL" = "fantasizer@gmail.com" ]
then
    cn="Felix Laurie von Massenbach"
    cm="felix@erbridge.co.uk"
fi
if [ "$GIT_AUTHOR_EMAIL" = "fantasizer@gmail.com" ]
then
    an="Felix Laurie von Massenbach"
    am="felix@erbridge.co.uk"
fi
 
export GIT_AUTHOR_NAME="$an"
export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_NAME="$cn"
export GIT_COMMITTER_EMAIL="$cm"
'
